# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField(default='')),
                ('phone', models.IntegerField(default='')),
                ('emailid', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
